-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgS5YG8RxdvoUIjffE
HWiprgfZz81x2bcRoOL6DOAPOMmgCgYIKoZIzj0DAQehRANCAATsd2kUYjI6Bf7l
rY+WWsH7ETSaypJKSdtTfR0vq4TNtjoVKjW5cxDfx5MkQt9NiqgROjp8Is5dB5YH
R6+wa4+/
-----END PRIVATE KEY-----